base: --no-source --color --format pretty -p html_report
default: --profile qa

qa: --profile base PROFILE=qa
prod: --profile base PROFILE=prod
dev: --profile base PROFILE=dev

html_report: --format progress --format html --out=report/features_report.html